-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 23:45:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actors` (
  `idActors` INT NOT NULL AUTO_INCREMENT,
  `ActorsFullName` VARCHAR(45) NOT NULL,
  `ActorsBirthday` date NOT NULL,
  PRIMARY KEY (`idActors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producers` (
  `ProducersId` INT NOT NULL AUTO_INCREMENT,
  `ProducersFullName` VARCHAR(45) NOT NULL,
  `ProducersBirthday` date NOT NULL,
  PRIMARY KEY (`ProducersId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Films` (
  `FilmId` INT NOT NULL AUTO_INCREMENT,
  `FilmName` VARCHAR(45) NOT NULL,
  `ActorName` VARCHAR(45) NOT NULL,
  `ReleaseDate` date NOT NULL,
  `ReleaseCountry` VARCHAR(45) NOT NULL,
  `idActors` INT NOT NULL,
  `idProducers` INT NOT NULL,
  PRIMARY KEY (`FilmId`),
  INDEX `idActors_idx` (`idActors` ASC) VISIBLE,
  INDEX `idProducers_idx` (`idProducers` ASC) VISIBLE,
  CONSTRAINT `idActors`
    FOREIGN KEY (`idActors`)
    REFERENCES `mydb`.`Actors` (`idActors`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idProducers`
    FOREIGN KEY (`idProducers`)
    REFERENCES `mydb`.`Producers` (`ProducersId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
